/* CopySet ERP — canonical archive for invoiced orders. */
(function(){
 const root=window.CopySet=window.CopySet||{},ui={query:''};
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const num=v=>(root.parseNumber?.(v,0)??Number(v))||0;
 const products=o=>Array.isArray(o.products)&&o.products.length?o.products:[{name:o.product||'Tuote',qty:o.qty||0,price:o.price||0}];
 const total=o=>products(o).reduce((s,p)=>s+num(p.price),0)+num(o.setupFee)+num(o.billingFee)+num(o.deliveryPrice||o.deliveryFee);
 function render(){const host=document.getElementById('archive');if(!host)return;let rows=(root.orders?.()||[]).filter(o=>o.mode!=='Tarjous'&&o.status==='Laskutettu').sort((a,b)=>String(b.date||'').localeCompare(String(a.date||'')));if(ui.query.trim()){const q=ui.query.toLocaleLowerCase('fi-FI');rows=rows.filter(o=>[o.no,o.company,o.orderReference,o.date,...products(o).flatMap(p=>[p.name,p.qty])].some(v=>String(v??'').toLocaleLowerCase('fi-FI').includes(q)))}host.innerHTML=`<div class="card"><div class="toolbar"><div><h2 style="margin:0">Arkisto / vanhat tilaukset</h2><div class="small">Hae laskutettu työ ja kopioi se uudeksi muokattavaksi tilaukseksi.</div></div></div><div class="toolbar" style="margin-top:12px"><input id="archiveSearch" placeholder="Hae asiakas, tilausnumero, tuote, viite tai päivämäärä" value="${esc(ui.query)}"></div><div class="tablewrap"><table><thead><tr><th>Tilaus</th><th>Päivä</th><th>Asiakas</th><th>Tuotteet</th><th>Myynti alv 0</th><th></th></tr></thead><tbody>${rows.length?rows.map(o=>`<tr data-archive-open="${esc(o.id)}"><td><b>${esc(o.no)}</b></td><td>${esc(root.formatDate?.(o.date)||o.date)}</td><td>${esc(o.company)}</td><td>${products(o).map(p=>`${esc(p.name)} · ${esc(p.qty)} kpl`).join('<br>')}</td><td>${root.formatMoney?.(total(o))||total(o)}</td><td><button class="btn orange" data-archive-copy="${esc(o.id)}">Kopioi uudeksi</button></td></tr>`).join(''):'<tr><td colspan="6"><div class="order-empty">Arkistosta ei löytynyt töitä.</div></td></tr>'}</tbody></table></div></div>`;host.querySelectorAll('[data-archive-open]').forEach(row=>row.onclick=()=>root.orderPage?.open?.(row.dataset.archiveOpen));host.querySelectorAll('[data-archive-copy]').forEach(button=>button.onclick=e=>{e.stopPropagation();root.orderCommands?.duplicate?.(button.dataset.archiveCopy)});const input=host.querySelector('#archiveSearch');if(input)input.oninput=e=>{ui.query=e.target.value;render();const next=host.querySelector('#archiveSearch');next?.focus();next?.setSelectionRange(next.value.length,next.value.length)}}root.archiveUi=ui;root.renderArchive=render;window.renderArchive=render;
})();
