/* CopySet ERP — canonical customer order confirmation. */
(function(){
 const root=window.CopySet=window.CopySet||{};
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const money=v=>root.formatMoney?root.formatMoney(v):(Number(v)||0).toFixed(2)+' €',date=v=>root.formatDate?.(v)||String(v||'—');
 const products=o=>Array.isArray(o.products)&&o.products.length?o.products:[{name:o.product,qty:o.qty,price:o.price,desc:o.description}];
 function html(o){const t=root.invoiceReview?.calculate?.(o)||{net:Number(o.price)||0,vat:0,total:Number(o.price)||0},ds=Array.isArray(o.deliveries)?o.deliveries:[],ps=products(o);return `<article class="confirmdoc"><header class="confhead"><div class="conflogo">COPY<span>-SET</span></div><div class="conftitle">TILAUSVAHVISTUS<small>${esc(o.no||'')}</small></div></header><div class="confbar"></div><div class="confgrid"><div><div class="conflabel">ASIAKAS</div><b>${esc(o.company)}</b><br>${esc(o.contact)}<br>${esc(o.email)}<br>${esc(o.phone)}</div><div><div class="conflabel">TILAUSTIEDOT</div><b>Tilausnumero:</b> ${esc(o.no)}<br><b>Tilauspäivä:</b> ${date(o.date)}<br><b>Toimitus:</b> ${date(o.deliveryDate||o.deadline)}<br><b>Deadline:</b> ${date(o.deadline)}</div></div><div class="confsection"><div class="conflabel">TUOTTEET</div><table class="conftable"><tr><th>Tuote</th><th>Määrä</th><th>Hinta alv 0 %</th></tr>${ps.map(p=>`<tr><td><b>${esc(p.name||'Tuote')}</b>${p.desc?`<br><small>${esc(p.desc)}</small>`:''}</td><td>${esc(p.qty||0)} kpl</td><td>${money(p.price)}</td></tr>`).join('')}</table></div><div class="confgrid"><div><div class="conflabel">TOIMITUSOSOITE${ds.length>1?'ET':''}</div>${ds.length?ds.map((d,i)=>`<div style="margin-bottom:8px"><b>${ds.length>1?`${i+1}. `:''}${esc(d.recipient||o.company)}</b><br>${esc(d.address)}<br>${esc(d.zip)} ${esc(d.city)} ${esc(d.country||'Suomi')}</div>`).join(''):'Nouto / ei toimitusosoitetta'}</div><div><div class="conflabel">LASKUTUS</div>${esc(o.billingAddress||'—')}<br><b>Maksuehto:</b> ${esc(o.paymentTerms||o.paymentTerm||`${root.config?.paymentTermsDays||21} pv`)}</div></div><div class="confprice"><div><span>Veroton yhteensä</span><b>${money(t.net)}</b></div><div><span>ALV ${String(t.vatRate??root.config?.domesticVat??25.5).replace('.',',')} %</span><b>${money(t.vat)}</b></div><div class="total"><span>Yhteensä</span><b>${money(t.total)}</b></div></div><div class="confnote"><b>Kiitos tilauksesta.</b> Tarkistathan tiedot ja ilmoita mahdollisista muutoksista mahdollisimman pian.</div><div class="conffoot">Copy-Set Oy</div></article>`}
 function print(id){const o=root.getOrder?.(id);if(!o||o.mode==='Tarjous')return false;const w=window.open('','_blank');if(!w)return alert('Salli ponnahdusikkuna asiakirjaa varten.');w.document.write(`<!doctype html><meta charset="utf-8"><title>Tilausvahvistus ${esc(o.no)}</title><link rel="stylesheet" href="/styles/documents.css"><body>${html(o)}<script>onload=()=>print()<\/script></body>`);w.document.close();return true}
 function open(id){const o=root.getOrder?.(id);if(!o||o.mode==='Tarjous')return false;const modal=document.getElementById('modal'),mt=document.getElementById('mt'),mb=document.getElementById('mb');if(!modal||!mt||!mb)return print(id);mt.textContent=`Tilausvahvistus · ${o.no||''}`;mb.innerHTML=`${html(o)}<div class="actions" style="margin-top:14px"><button type="button" class="btn dark" id="copysetConfirmPrint">🖨 Tulosta / PDF</button><button type="button" class="btn" id="copysetConfirmBack">Takaisin tilaukseen</button></div>`;modal.classList.add('on');mb.querySelector('#copysetConfirmPrint').onclick=()=>print(id);mb.querySelector('#copysetConfirmBack').onclick=()=>{modal.classList.remove('on');root.orderPage?.open?.(id)};return true}
 root.confirmation=Object.freeze({html,open,print});
})();