/* CopySet ERP consolidated order actions */
(function(){
 function orderById(id){return window.st&&Array.isArray(st.orders)?st.orders.find(x=>x.id===id):null}
 function persist(){if(typeof window.save==='function')save();if(typeof window.renderAll==='function')renderAll()}
 function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
 function fi(v){if(!v)return '—';try{return typeof window.FI_DATE==='function'?window.FI_DATE(v):v}catch(_e){return v}}
 function products(o){return Array.isArray(o.products)&&o.products.length?o.products:[{name:o.product,qty:o.qty,desc:o.description,extras:o.extraLines||[]}]}
 function field(p,names){for(const n of names){if(p&&p[n]!=null&&p[n]!=='')return p[n]}return ''}
 window.copysetDeleteOrder=function(id){const o=orderById(id);if(!o)return;if(!confirm('Poistetaanko '+(o.mode==='Tarjous'?'tarjous ':'tilaus ')+(o.no||'')+'?'))return;st.orders=st.orders.filter(x=>x.id!==id);if(typeof window.save==='function')save();if(typeof window.closeM==='function')closeM();if(typeof window.renderAll==='function')renderAll()};
 window.copysetSetProductionStep=function(id,step){if(!['Aloitettu','Käynnissä','Valmis'].includes(step))return;const o=orderById(id);if(!o)return;o.productionStep=step;persist();openOrder(id)};

 function technicalRows(p){const specs=[['Koko',field(p,['size','format','koko'])],['Materiaali / paperi',field(p,['material','paper','materiaali','paperi'])],['Värit',field(p,['colors','colour','color','varit','värit'])],['Painatus',field(p,['printing','print','painatus'])],['Jälkikäsittely',field(p,['finishing','finish','jalkikasittely','jälkikäsittely'])]];return specs.filter(x=>x[1]).map(x=>'<div class="spec"><span>'+esc(x[0])+'</span><b>'+esc(x[1])+'</b></div>').join('')}
 function productionCard(o){const ps=products(o),ds=Array.isArray(o.deliveries)?o.deliveries:[],vendor=o.production==='Alihankkija'&&typeof window.V==='function'?(V(o.supplierId)?.name||'Alihankkija'):'Copy-Set';const phtml=ps.map((p,i)=>{const extras=Array.isArray(p.extras)?p.extras:[];return '<section class="product"><div class="productTop"><div><small>TUOTE '+(i+1)+'</small><h2>'+esc(p.name||'Tuote')+'</h2></div><div class="qty">'+esc(p.qty||'—')+'<small>KPL</small></div></div><div class="specgrid">'+technicalRows(p)+'</div>'+(p.desc?'<div class="instruction"><span>TYÖOHJE / AINEISTO</span>'+esc(p.desc)+'</div>':'')+'<div class="tasks"><span>TYÖVAIHEET / LISÄTYÖT</span>'+(extras.length?extras.map(x=>'<label>□ '+esc(typeof x==='string'?x:(x.label||x.name||x.desc||'Lisätyö'))+'</label>').join(''):'<label>□ Ei erillisiä lisätöitä</label>')+'</div></section>'}).join('');const deliveries=ds.length?ds.map((d,i)=>'<div class="delivery"><b>'+esc((i+1)+'. '+(d.recipient||o.company||''))+'</b><br>'+esc(d.address||'')+'<br>'+esc((d.zip||'')+' '+(d.city||''))+(d.country?'<br>'+esc(d.country):'')+(d.qty?'<br>Määrä: '+esc(d.qty)+' kpl':'')+(d.info?'<br>Ohje: '+esc(d.info):'')+'</div>').join(''):'<div class="delivery"><b>'+esc(o.shipping||'Nouto')+'</b></div>';return '<main class="card"><header><div class="brand">COPY<span>-SET</span><small>PRINT OS</small></div><div class="title"><h1>TYÖKORTTI TUOTANTOON</h1><b>'+esc(o.no||'')+'</b></div></header><div class="orangeLine"></div><section class="meta"><div><span>TILAUS</span><b>'+esc(o.no||'')+'</b></div><div><span>ASIAKAS</span><b>'+esc(o.company||'')+'</b></div><div><span>DEADLINE</span><b>'+esc(fi(o.deadline))+'</b></div><div><span>TUOTANTO</span><b>'+esc(vendor)+'</b></div></section>'+phtml+'<section class="section"><h3>TOIMITUS</h3>'+deliveries+'</section><section class="section"><h3>TUOTANNON SEURANTA</h3><div class="checks"><label>□ Aineisto tarkistettu</label><label>□ Tulostettu</label><label>□ Jälkikäsittely</label><label>□ Pakattu</label><label>□ Valmis</label></div></section></main>'}
 const workCss='@page{size:A4;margin:12mm}*{box-sizing:border-box}body{margin:0;font-family:Arial,sans-serif;color:#202428}.card{max-width:900px;margin:auto}header{display:flex;justify-content:space-between;align-items:flex-start}.brand{font-size:28px;font-weight:950}.brand>span{color:#ef7f1a}.brand small{display:block;font-size:9px;letter-spacing:.25em;color:#777;margin-top:3px}.title{text-align:right}.title h1{font-size:22px;margin:0 0 5px}.orangeLine{height:6px;background:#ef7f1a;margin:14px 0 18px}.meta{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.meta>div,.spec{border:1px solid #d9dde1;padding:9px;border-radius:7px}.meta span,.spec span,.instruction span,.tasks>span{display:block;font-size:9px;font-weight:800;color:#69727b;letter-spacing:.05em;margin-bottom:4px}.product{border:2px solid #25292d;border-radius:9px;margin-top:16px;overflow:hidden;page-break-inside:avoid}.productTop{display:flex;justify-content:space-between;align-items:center;background:#f3f4f5;padding:10px 12px}.productTop small{font-size:9px;color:#69727b}.productTop h2{font-size:18px;margin:2px 0}.qty{font-size:25px;font-weight:950;text-align:right}.qty small{display:block;font-size:8px}.specgrid{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;padding:10px}.instruction,.tasks{padding:10px 12px;border-top:1px solid #ddd;line-height:1.45}.tasks label{display:block;padding:3px 0}.section{margin-top:18px}.section h3{font-size:10px;color:#69727b;letter-spacing:.08em;border-bottom:1px solid #ddd;padding-bottom:5px}.delivery{line-height:1.4;margin:7px 0}.checks{display:grid;grid-template-columns:repeat(2,1fr);gap:7px}.checks label{border:1px solid #d9dde1;border-radius:7px;padding:9px;font-weight:700}@media print{body{-webkit-print-color-adjust:exact;print-color-adjust:exact}}';
 function printProductionCard(id){const o=orderById(id);if(!o)return;const w=window.open('','_blank');if(!w)return alert('Salli ponnahdusikkuna tulostusta varten.');w.document.open();w.document.write('<!doctype html><html><head><meta charset="utf-8"><title>Työkortti '+esc(o.no||'')+'</title><style>'+workCss+'</style></head><body>'+productionCard(o)+'<script>window.onload=function(){window.print()}<\/script></body></html>');w.document.close()}
 window.productionDocHtml=productionCard;window.copysetPrintWorkCard=printProductionCard;window.showProductionDoc=printProductionCard;

 const oldCreateOrderFromQuote=window.createOrderFromQuote;if(typeof oldCreateOrderFromQuote==='function')window.createOrderFromQuote=function(id,withChanges){const q=orderById(id),before=q&&q.convertedOrderId,r=oldCreateOrderFromQuote.apply(this,arguments);if(q&&!before&&q.convertedOrderId&&!withChanges){const o=orderById(q.convertedOrderId);if(o){o.mode='Tilaus';o.status='Vahvistettu';o.artworkStatus='Aineisto OK';o.productionStep='Aloitettu';persist();setTimeout(()=>openOrder(o.id),0)}}return r};
 window.copysetStartProduction=function(id){const o=orderById(id);if(!o)return;const ps=products(o),essential=[];if(!o.company)essential.push('asiakas');if(!o.deadline)essential.push('deadline');if(!ps.length||ps.some(p=>!p.name))essential.push('tuote');if(ps.some(p=>!(+p.qty>0)))essential.push('määrä');if(essential.length){if(typeof window.openOrder==='function')openOrder(id);return alert('Täydennä tuotantoa varten: '+essential.join(', ')+'.')}o.mode='Tilaus';o.artworkStatus='Aineisto OK';o.status='Tuotannossa';o.productionStep='Aloitettu';if(typeof window.logEvent==='function')try{logEvent(o,'Tuotanto aloitettu')}catch(_e){}persist();if(typeof window.openOrder==='function')openOrder(id)};
 /* The list's Aloita tuotanto used legacy v2Advance -> missingFor, which required billing/customer fields not needed for production. Route Vahvistettu directly to the production transition. */
 const legacyV2Advance=window.v2Advance;window.v2Advance=function(id){const o=orderById(id);if(o&&o.status==='Vahvistettu')return window.copysetStartProduction(id);return typeof legacyV2Advance==='function'?legacyV2Advance.apply(this,arguments):undefined};
 function decorateOrder(id){const o=orderById(id),body=document.getElementById('mb');if(!o||!body)return;body.querySelectorAll('button').forEach(b=>{const t=(b.textContent||'').toLowerCase(),code=(b.getAttribute('onclick')||'').toLowerCase();if(t.includes('työkortti')||t.includes('tulosta tuotantoon')||code.includes('showproductiondoc')){b.textContent='🖨 Tulosta työkortti tuotantoon';b.removeAttribute('onclick');b.onclick=()=>printProductionCard(id)}});if(o.mode==='Tilaus'&&['Vahvistettu','Tuotannossa','Valmis'].includes(o.status)){const groups=[...body.querySelectorAll('.actions')],a=groups[groups.length-1];if(a&&!a.querySelector('.copyset-workcard')){const b=document.createElement('button');b.type='button';b.className='btn dark copyset-workcard';b.textContent='🖨 Tulosta työkortti tuotantoon';b.onclick=()=>printProductionCard(id);a.prepend(b)}}if(o.status==='Vahvistettu'){const groups=[...body.querySelectorAll('.actions')],a=groups[groups.length-1];if(a&&!a.querySelector('.copyset-production-start')){const b=document.createElement('button');b.type='button';b.className='btn orange copyset-production-start';b.textContent='→ Siirrä tuotantoon';b.onclick=()=>copysetStartProduction(id);a.append(b)}}if(o.status==='Tuotannossa'&&!body.querySelector('#copyset-production-steps')){const cur=o.productionStep||'Aloitettu',card=document.createElement('div');card.className='card';card.id='copyset-production-steps';card.innerHTML='<h3>Tuotannon eteneminen</h3><div class="actions">'+['Aloitettu','Käynnissä','Valmis'].map(s=>'<button type="button" class="btn '+(cur===s?'orange':'')+'" data-production-step="'+s+'">'+(cur===s?'✓ ':'')+s+'</button>').join('')+'</div>';card.querySelectorAll('[data-production-step]').forEach(b=>b.onclick=()=>copysetSetProductionStep(id,b.dataset.productionStep));const wf=body.querySelector('.wf');if(wf)wf.insertAdjacentElement('afterend',card);else body.prepend(card)}const groups=[...body.querySelectorAll('.actions')],actions=groups[groups.length-1];if(actions&&!actions.querySelector('.copyset-delete')){const b=document.createElement('button');b.type='button';b.className='btn danger copyset-delete';b.textContent='Poista '+(o.mode==='Tarjous'?'tarjous':'tilaus');b.onclick=()=>copysetDeleteOrder(id);actions.prepend(b)}if(typeof window.copysetEnhancePricing==='function')copysetEnhancePricing()}
 const baseOpenOrder=window.openOrder;if(typeof baseOpenOrder==='function')window.openOrder=function(id){const r=baseOpenOrder.apply(this,arguments);queueMicrotask(()=>decorateOrder(id));return r};
})();