/* CopySet ERP consolidated order actions */
(function(){
 function state(){try{return typeof st!=='undefined'?st:window.st}catch(_e){return window.st}}
 function orderById(id){const s=state();return s&&Array.isArray(s.orders)?s.orders.find(x=>String(x.id)===String(id)):null}
 function persist(){if(typeof save==='function')save();if(typeof renderAll==='function')renderAll()}
 function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
 function fi(v){if(!v)return '—';try{return typeof FI_DATE==='function'?FI_DATE(v):v}catch(_e){return v}}
 function products(o){return Array.isArray(o.products)&&o.products.length?o.products:[{name:o.product,qty:o.qty,desc:o.description,extras:o.extraLines||[]}]}
 function field(p,names){for(const n of names){if(p&&p[n]!=null&&p[n]!=='')return p[n]}return ''}
 window.copysetDeleteOrder=function(id){const o=orderById(id),s=state();if(!o||!s)return;if(!confirm('Poistetaanko '+(o.mode==='Tarjous'?'tarjous ':'tilaus ')+(o.no||'')+'?'))return;s.orders=s.orders.filter(x=>String(x.id)!==String(id));persist();if(typeof closeM==='function')closeM()};
 window.copysetSetProductionStep=function(id,step){if(!['Aloitettu','Käynnissä','Valmis'].includes(step))return;const o=orderById(id);if(!o)return;o.productionStep=step;persist();if(typeof openOrder==='function')openOrder(id)};
 function technicalRows(p){const specs=[['Koko',field(p,['size','format','koko'])],['Materiaali / paperi',field(p,['material','paper','materiaali','paperi'])],['Värit',field(p,['colors','colour','color','varit','värit'])],['Painatus',field(p,['printing','print','painatus'])],['Jälkikäsittely',field(p,['finishing','finish','jalkikasittely','jälkikäsittely'])]];return specs.filter(x=>x[1]).map(x=>'<div class="spec"><span>'+esc(x[0])+'</span><b>'+esc(x[1])+'</b></div>').join('')}
 function productionCard(o){const ps=products(o),ds=Array.isArray(o.deliveries)?o.deliveries:[],vendor=o.production==='Alihankkija'&&typeof V==='function'?(V(o.supplierId)?.name||'Alihankkija'):'Copy-Set';const phtml=ps.map((p,i)=>{const extras=Array.isArray(p.extras)?p.extras:[];return '<section class="product"><div class="productTop"><div><small>TUOTE '+(i+1)+'</small><h2>'+esc(p.name||'Tuote')+'</h2></div><div class="qty">'+esc(p.qty||'—')+'<small>KPL</small></div></div><div class="specgrid">'+technicalRows(p)+'</div>'+(p.desc?'<div class="instruction"><span>TYÖOHJE / AINEISTO</span>'+esc(p.desc)+'</div>':'')+'<div class="tasks"><span>TYÖVAIHEET / LISÄTYÖT</span>'+(extras.length?extras.map(x=>'<label>□ '+esc(typeof x==='string'?x:(x.label||x.name||x.desc||'Lisätyö'))+'</label>').join(''):'<label>□ Ei erillisiä lisätöitä</label>')+'</div></section>'}).join('');const deliveries=ds.length?ds.map((d,i)=>'<div class="delivery"><b>'+esc((i+1)+'. '+(d.recipient||o.company||''))+'</b><br>'+esc(d.address||'')+'<br>'+esc((d.zip||'')+' '+(d.city||''))+(d.country?'<br>'+esc(d.country):'')+(d.qty?'<br>Määrä: '+esc(d.qty)+' kpl':'')+(d.info?'<br>Ohje: '+esc(d.info):'')+'</div>').join(''):'<div class="delivery"><b>'+esc(o.shipping||'Nouto')+'</b></div>';return '<main class="card"><header><div class="brand">COPY<span>-SET</span><small>PRINT OS</small></div><div class="title"><h1>TYÖKORTTI TUOTANTOON</h1><b>'+esc(o.no||'')+'</b></div></header><div class="orangeLine"></div><section class="meta"><div><span>TILAUS</span><b>'+esc(o.no||'')+'</b></div><div><span>ASIAKAS</span><b>'+esc(o.company||'')+'</b></div><div><span>DEADLINE</span><b>'+esc(fi(o.deadline))+'</b></div><div><span>TUOTANTO</span><b>'+esc(vendor)+'</b></div></section>'+phtml+'<section class="section"><h3>TOIMITUS</h3>'+deliveries+'</section><section class="section"><h3>TUOTANNON SEURANTA</h3><div class="checks"><label>□ Aineisto tarkistettu</label><label>□ Tulostettu</label><label>□ Jälkikäsittely</label><label>□ Pakattu</label><label>□ Valmis</label></div></section></main>'}
 const workCss='@page{size:A4;margin:12mm}*{box-sizing:border-box}body{margin:0;font-family:Arial,sans-serif;color:#202428}.card{max-width:900px;margin:auto}header{display:flex;justify-content:space-between;align-items:flex-start}.brand{font-size:28px;font-weight:950}.brand>span{color:#ef7f1a}.brand small{display:block;font-size:9px;letter-spacing:.25em;color:#777;margin-top:3px}.title{text-align:right}.title h1{font-size:22px;margin:0 0 5px}.orangeLine{height:6px;background:#ef7f1a;margin:14px 0 18px}.meta{display:grid;grid-template-columns:repeat(4,1fr);gap:8px}.meta>div,.spec{border:1px solid #d9dde1;padding:9px;border-radius:7px}.meta span,.spec span,.instruction span,.tasks>span{display:block;font-size:9px;font-weight:800;color:#69727b;letter-spacing:.05em;margin-bottom:4px}.product{border:2px solid #25292d;border-radius:9px;margin-top:16px;overflow:hidden;page-break-inside:avoid}.productTop{display:flex;justify-content:space-between;align-items:center;background:#f3f4f5;padding:10px 12px}.productTop small{font-size:9px;color:#69727b}.productTop h2{font-size:18px;margin:2px 0}.qty{font-size:25px;font-weight:950;text-align:right}.qty small{display:block;font-size:8px}.specgrid{display:grid;grid-template-columns:repeat(3,1fr);gap:7px;padding:10px}.instruction,.tasks{padding:10px 12px;border-top:1px solid #ddd;line-height:1.45}.tasks label{display:block;padding:3px 0}.section{margin-top:18px}.section h3{font-size:10px;color:#69727b;letter-spacing:.08em;border-bottom:1px solid #ddd;padding-bottom:5px}.delivery{line-height:1.4;margin:7px 0}.checks{display:grid;grid-template-columns:repeat(2,1fr);gap:7px}.checks label{border:1px solid #d9dde1;border-radius:7px;padding:9px;font-weight:700}@media print{body{-webkit-print-color-adjust:exact;print-color-adjust:exact}}';
 function printProductionCard(id){const o=orderById(id);if(!o)return;const w=window.open('','_blank');if(!w)return alert('Salli ponnahdusikkuna tulostusta varten.');w.document.open();w.document.write('<!doctype html><html><head><meta charset="utf-8"><title>Työkortti '+esc(o.no||'')+'</title><style>'+workCss+'</style></head><body>'+productionCard(o)+'<script>window.onload=function(){window.print()}<\/script></body></html>');w.document.close()}
 window.productionDocHtml=productionCard;window.copysetPrintWorkCard=printProductionCard;window.showProductionDoc=printProductionCard;
 const oldCreateOrderFromQuote=window.createOrderFromQuote;if(typeof oldCreateOrderFromQuote==='function')window.createOrderFromQuote=function(id,withChanges){const q=orderById(id),before=q&&q.convertedOrderId,r=oldCreateOrderFromQuote.apply(this,arguments);if(q&&!before&&q.convertedOrderId&&!withChanges){const o=orderById(q.convertedOrderId);if(o){o.mode='Tilaus';o.status='Vahvistettu';o.artworkStatus='Aineisto OK';o.productionStep='Aloitettu';persist();setTimeout(()=>openOrder(o.id),0)}}return r};
 window.copysetStartProduction=function(id){const o=orderById(id);if(!o)return;o.mode='Tilaus';o.artworkStatus='Aineisto OK';o.status='Tuotannossa';o.productionStep='Aloitettu';if(typeof logEvent==='function')try{logEvent(o,'Tuotanto aloitettu')}catch(_e){}persist();if(typeof window.copysetOpenOrderPage==='function')window.copysetOpenOrderPage(id)};
 const legacyV2Advance=window.v2Advance;window.v2Advance=function(id){const o=orderById(id);if(o&&o.status==='Vahvistettu')return window.copysetStartProduction(id);return typeof legacyV2Advance==='function'?legacyV2Advance.apply(this,arguments):undefined};
})();