/* CopySet ERP — canonical dashboard and business intelligence. */
(function(){
 const root=window.CopySet=window.CopySet||{},ui={preset:'month',from:'',to:''};
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const num=v=>(root.parseNumber?.(v,0)??Number(v))||0;
 const money=v=>root.formatMoney?.(v)||num(v).toLocaleString('fi-FI',{style:'currency',currency:'EUR'});
 const date=v=>root.parseDate?.(v);
 const products=o=>Array.isArray(o.products)&&o.products.length?o.products:[{name:o.product||'Muu',price:o.price||0,qty:o.qty||0}];
 function bounds(){const now=new Date(),end=new Date(now.getFullYear(),now.getMonth(),now.getDate()),start=new Date(end);if(ui.preset==='day'){}else if(ui.preset==='week')start.setDate(start.getDate()-6);else if(ui.preset==='month')start.setDate(1);else if(ui.preset==='year')start.setMonth(0,1);else{const a=date(ui.from),b=date(ui.to);return{start:a||null,end:b||null}}end.setHours(23,59,59,999);return{start,end}}
 function rows(){const {start,end}=bounds();return(root.orders?.()||[]).filter(o=>o.mode!=='Tarjous').filter(o=>{const d=date(o.date);return d&&(!start||d>=start)&&(!end||d<=end)})}
 function net(o){return products(o).reduce((s,p)=>s+num(p.price),0)+num(o.setupFee)+num(o.billingFee)+num(o.deliveryPrice||o.deliveryFee)}
 function group(list,key){const m=new Map();list.forEach(o=>{const k=key(o)||'Muu';m.set(k,(m.get(k)||0)+net(o))});return[...m.entries()].sort((a,b)=>b[1]-a[1])}
 function barRows(data){const max=Math.max(1,...data.map(x=>x[1]));return data.slice(0,10).map(([label,value])=>`<div style="display:grid;grid-template-columns:minmax(120px,1.3fr) 3fr auto;gap:10px;align-items:center;margin:10px 0"><b>${esc(label)}</b><div style="height:12px;background:#eceff2;border-radius:99px;overflow:hidden"><span style="display:block;width:${Math.max(2,value/max*100)}%;height:100%;background:#ef7f1a"></span></div><span>${money(value)}</span></div>`).join('')||'<p class="small">Ei myyntiä valitulla ajanjaksolla.</p>'}
 function render(){const host=document.getElementById('dashboard');if(!host)return;const list=rows(),sales=list.reduce((s,o)=>s+net(o),0),inProduction=list.filter(o=>o.status==='Tuotannossa').length,ready=list.filter(o=>['Valmis','Laskutusvalmis'].includes(o.status)).length,invoiced=list.filter(o=>o.status==='Laskutettu').length,byProduct=new Map();list.forEach(o=>products(o).forEach(p=>byProduct.set(p.name||'Muu',(byProduct.get(p.name||'Muu')||0)+num(p.price))));const productData=[...byProduct.entries()].sort((a,b)=>b[1]-a[1]),customerData=group(list,o=>o.company||'Tuntematon asiakas');host.innerHTML=`<div class="card"><div class="toolbar"><div><h2 style="margin:0">Dashboard</h2><div class="small">Myynti, tuotteet ja asiakkaat valitulla ajanjaksolla.</div></div><div class="actions" data-dashboard-presets>${[['day','Päivä'],['week','Viikko'],['month','Kuukausi'],['year','Vuosi'],['custom','Oma väli']].map(x=>`<button class="btn ${ui.preset===x[0]?'orange':''}" data-preset="${x[0]}">${x[1]}</button>`).join('')}</div></div><div class="form" style="margin-top:12px;${ui.preset==='custom'?'':'display:none'}" data-dashboard-range><div><div class="lab">Alkaen</div><input id="dashboardFrom" inputmode="numeric" placeholder="pp.kk.vvvv" value="${esc(ui.from)}"></div><div><div class="lab">Saakka</div><input id="dashboardTo" inputmode="numeric" placeholder="pp.kk.vvvv" value="${esc(ui.to)}"></div><div><button class="btn orange" id="dashboardApply" style="margin-top:20px">Näytä</button></div></div></div><div class="metrics"><div class="card metric"><span>Tilauksia</span><b>${list.length}</b></div><div class="card metric"><span>Myynti alv 0</span><b>${money(sales)}</b></div><div class="card metric"><span>Tuotannossa</span><b>${inProduction}</b></div><div class="card metric"><span>Valmiina</span><b>${ready}</b></div><div class="card metric"><span>Laskutettu</span><b>${invoiced}</b></div></div><div class="dashboard-bi-grid"><div class="card"><h3>Myynti tuoteryhmittäin</h3>${barRows(productData)}</div><div class="card"><h3>Myynti asiakkaittain</h3>${barRows(customerData)}</div></div>`;host.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>{ui.preset=b.dataset.preset;render()});host.querySelector('#dashboardApply')?.addEventListener('click',()=>{ui.from=host.querySelector('#dashboardFrom')?.value||'';ui.to=host.querySelector('#dashboardTo')?.value||'';render()})}
 root.dashboardUi=ui;root.renderDashboard=render;window.renderDashboard=render;
})();
