/* CopySet ERP — canonical dashboard and business intelligence. */
(function(){
 const root=window.CopySet=window.CopySet||{},ui={preset:'month',from:'',to:''};
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const num=v=>(root.parseNumber?.(v,0)??Number(v))||0;
 const money=v=>root.formatMoney?.(v)||num(v).toLocaleString('fi-FI',{style:'currency',currency:'EUR'});
 const date=v=>root.parseDate?.(v);
 const products=o=>Array.isArray(o.products)&&o.products.length?o.products:[{name:o.product||'Muu',price:o.price||0,qty:o.qty||0}];
 function bounds(){const now=new Date(),end=new Date(now.getFullYear(),now.getMonth(),now.getDate()),start=new Date(end);if(ui.preset==='day'){}else if(ui.preset==='week')start.setDate(start.getDate()-6);else if(ui.preset==='month')start.setDate(1);else if(ui.preset==='year')start.setMonth(0,1);else{const a=date(ui.from),b=date(ui.to);return{start:a||null,end:b||null}}end.setHours(23,59,59,999);return{start,end}}
 function rows(){const {start,end}=bounds();return(root.orders?.()||[]).filter(o=>o.mode!=='Tarjous').filter(o=>{const d=date(o.date);return d&&(!start||d>=start)&&(!end||d<=end)})}
 function net(o){return products(o).reduce((s,p)=>s+num(p.price),0)+num(o.setupFee)+num(o.billingFee)+num(o.deliveryPrice||o.deliveryFee)}
 function group(list,key){const m=new Map();list.forEach(o=>{const k=key(o)||'Muu';m.set(k,(m.get(k)||0)+net(o))});return[...m.entries()].sort((a,b)=>b[1]-a[1])}
 function barRows(data){const max=Math.max(1,...data.map(x=>x[1]));return data.slice(0,8).map(([label,value],i)=>`<div class="copyset-chart-row"><span class="copyset-chart-rank">${i+1}</span><b>${esc(label)}</b><div class="copyset-chart-track"><i style="width:${Math.max(3,value/max*100)}%"></i></div><strong>${money(value)}</strong></div>`).join('')||'<div class="copyset-register-empty">Ei myyntiä valitulla ajanjaksolla.</div>'}
 function render(){const host=document.getElementById('dashboard');if(!host)return;const list=rows(),sales=list.reduce((s,o)=>s+net(o),0),inProduction=list.filter(o=>o.status==='Tuotannossa').length,ready=list.filter(o=>['Valmis','Laskutusvalmis'].includes(o.status)).length,invoiced=list.filter(o=>o.status==='Laskutettu').length,byProduct=new Map();list.forEach(o=>products(o).forEach(p=>byProduct.set(p.name||'Muu',(byProduct.get(p.name||'Muu')||0)+num(p.price))));const productData=[...byProduct.entries()].sort((a,b)=>b[1]-a[1]),customerData=group(list,o=>o.company||'Tuntematon asiakas'),average=list.length?sales/list.length:0;host.innerHTML=`<div class="copyset-page dashboard-pro"><section class="copyset-view-hero"><div><span class="copyset-eyebrow">LIIKETOIMINNAN TILANNE</span><h2>Dashboard</h2><p>Myynti, tuotanto, asiakkaat ja tuoteryhmät valitulla ajanjaksolla.</p></div><div class="copyset-periods">${[['day','Päivä'],['week','Viikko'],['month','Kuukausi'],['year','Vuosi'],['custom','Oma väli']].map(x=>`<button class="btn ${ui.preset===x[0]?'orange':''}" data-preset="${x[0]}">${x[1]}</button>`).join('')}</div></section><section class="copyset-date-range" ${ui.preset==='custom'?'':'hidden'}><label><span>Alkaen</span><input id="dashboardFrom" type="date" value="${esc(ui.from)}"></label><label><span>Saakka</span><input id="dashboardTo" type="date" value="${esc(ui.to)}"></label><button class="btn orange" id="dashboardApply">Näytä</button></section><div class="copyset-kpi-grid"><article class="copyset-kpi featured"><span>Myynti alv 0</span><b>${money(sales)}</b><small>${list.length} tilausta valitulla jaksolla</small></article><article class="copyset-kpi"><span>Keskimääräinen tilaus</span><b>${money(average)}</b><small>alv 0 %</small></article><article class="copyset-kpi"><span>Tuotannossa</span><b>${inProduction}</b><small>aktiivista työtä</small></article><article class="copyset-kpi"><span>Valmiina</span><b>${ready}</b><small>toimitukseen tai laskutukseen</small></article><article class="copyset-kpi"><span>Laskutettu</span><b>${invoiced}</b><small>tilausta</small></article></div><div class="copyset-insight-grid"><section class="copyset-insight-card"><header><div><span class="copyset-eyebrow">TUOTTEET</span><h3>Myynti tuoteryhmittäin</h3></div></header>${barRows(productData)}</section><section class="copyset-insight-card"><header><div><span class="copyset-eyebrow">ASIAKKAAT</span><h3>Myynti asiakkaittain</h3></div></header>${barRows(customerData)}</section></div></div>`;host.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>{ui.preset=b.dataset.preset;render()});host.querySelector('#dashboardApply')?.addEventListener('click',()=>{ui.from=host.querySelector('#dashboardFrom')?.value||'';ui.to=host.querySelector('#dashboardTo')?.value||'';render()})}
 root.dashboardUi=ui;root.renderDashboard=render;window.renderDashboard=render;
})();
