/* CopySet ERP — canonical demo data, persistence and shared globals. */
(function(){
  const STORAGE_KEY='copyset-customer-demo-v1';
  window.FLOW=['Tarjous','Vahvistettu','Tuotannossa','Valmis','Laskutusvalmis','Laskutettu'];
  window.P=[['Käyntikortit',.06,35],['Flyerit',.05,35],['Esitteet / taitetut',.08,45],['Vihkot / katalogit',.12,55],['Julisteet',.18,35],['Tarrat / etiketit',.09,45],['Kortit / kutsut',.08,35],['Kirjekuoret',.10,40],['Itsejäljentävät lomakkeet',.14,50],['Käyttöohjeet / manuaalit',.11,45],['Roll-upit',25,25],['Bannerit / banderollit',2.5,35],['Kyltit / levyt',3,45],['Ikkunateippaukset',4,55],['Ajoneuvoteippaukset',35,80],['Ruokalistat / menut',.12,45],['Rakennuspiirustukset',.25,25],['Esittelykansiot',.18,55],['Pöytäkolmiot / pöytämateriaalit',.14,40],['Suoramainonta / postitus',.20,60]];
  const day=n=>{const d=new Date();d.setDate(d.getDate()+n);return d.toISOString().slice(0,10)};
  const customers=()=>[['AS-1001','Nordic Design Oy','3124567-8','Anna Virtanen','anna@nordic.fi','040 123 4567','Mannerheimintie 18','00100','Helsinki'],['AS-1002','Bistro Satama Oy','2987654-1','Ville Hänninen','ville@bistro.fi','050 222 3344','Kanavaranta 4','00160','Helsinki'],['AS-1003','Lumen Studio Oy','3344556-2','Emilia Koski','emilia@lumen.fi','045 210 1103','Pursimiehenkatu 12','00150','Helsinki'],['AS-1004','Porvoon Autotalo Oy','2765432-9','Antti Rautio','antti@auto.fi','040 210 1104','Veckjärventie 8','06150','Porvoo'],['AS-1005','Aurora Events Oy','3011223-4','Noora Mäkinen','noora@aurora.fi','040 210 1107','Messuaukio 1','00520','Helsinki'],['AS-1006','Nordic Wellness Oy','3221100-7','Sara Lehto','sara@nw.fi','050 210 1105','Bulevardi 9','00120','Helsinki'],['AS-1007','Helsinki Coffee Oy','2877665-3','Oskari Laakso','oskari@coffee.fi','045 210 1109','Aleksanterinkatu 22','00170','Helsinki'],['AS-1008','Kivijalka Retail Oy','3144788-5','Mikko Kallio','mikko@retail.fi','044 210 1106','Runeberginkatu 31','00100','Helsinki'],['AS-1009','Merikivi Rakennus Oy','2699554-6','Petri Niemelä','petri@meri.fi','050 210 1108','Lauttasaarentie 15','00200','Helsinki'],['AS-1010','Aava Arkkitehdit Oy','2991887-2','Laura Salmi','laura@aava.fi','040 210 1101','Korkeavuorenkatu 28','00130','Helsinki']].map((a,i)=>({id:'c'+i,no:a[0],company:a[1],bid:a[2],contact:a[3],email:a[4],phone:a[5],address:a[6],zip:a[7],city:a[8],country:'Suomi',billing:`${a[6]}, ${a[7]} ${a[8]}`,terms:'21 pv',discount:i%4,status:'Aktiivinen',notes:'Esimerkkiasiakas · tiedot muokattavissa'}));
  const vendors=()=>['Helsingin Offsetpaino Oy|Offsetpaino','Nordic Label Works Oy|Tarrat','Suomen Suurkuva Oy|Suurkuva','ProBind Finland Oy|Sidonta','LaserCut Print Oy|Muotoonleikkaus','Premium Foil Oy|Foliointi','EcoPaper Print Oy|Ekologiset paperit','MailHouse Finland Oy|Postitus','SignPro Nordic Oy|Teippaukset','FastPrint Partner Oy|Kiiretyöt'].map((x,i)=>{const a=x.split('|');return{id:'v'+i,name:a[0],specialty:a[1],contact:'Yhteyshenkilö '+(i+1),email:`info${i+1}@example.fi`,phone:`040 100 10${i}`,address:`Teollisuustie ${i+1}, Helsinki`,lead:`${2+i%4}–${4+i%5} pv`}});
  function orders(cs,vs){const qs=['Luonnos','Valmis lähetettäväksi','Lähetetty','Hyväksytty','Hylätty'],os=['Vahvistettu','Tuotannossa','Valmis','Laskutusvalmis','Laskutettu'];return Array.from({length:40},(_,i)=>{const quote=i<20,j=quote?i:i-20,c=cs[i%cs.length],p=P[i%P.length],ship=['Posti','Lähetti','Nouto'][i%3],qty=[50,100,250,500,750,1000,2000,3000,5000][i%9],price=Math.round((150+i*23+(i%5)*70)*100)/100;return{id:'o'+i,no:(quote?'TAR-':'TIL-')+`2026-${String(2201+i).padStart(4,'0')}`,name:`DEMO ${i+1} · ${p[0]}`,mode:quote?'Tarjous':'Tilaus',quoteStage:quote?qs[j%qs.length]:undefined,offerStatus:quote?qs[j%qs.length]:undefined,customerId:c.id,date:day(-(i%18)),deadline:day((i%14)-2),valid:day(14),deliveryDate:day((i%10)+1),company:c.company,contact:c.contact,email:c.email,phone:c.phone,product:p[0],products:[{name:p[0],qty,price,desc:'Esimerkkityö asiakkaan testausta varten.',extras:i%3===0?['Laminointi','Leikkaus']:[]}],qty,price,setupFee:50,billingFee:6,vatRate:25.5,paymentTerms:'21 pv',deliveryPrice:ship==='Nouto'?0:ship==='Posti'?12.9:35,status:quote?'Tarjous':os[j%os.length],production:i%4===0?'Alihankkija':'Copy-Set',productionStep:!quote&&os[j%os.length]==='Tuotannossa'?['Aloitettu','Käynnissä'][j%2]:'',supplierId:i%4===0?vs[i%vs.length].id:'',shipping:ship,description:'Esimerkkityö asiakkaan testausta varten.',demo:true,contacts:[],deliveries:[{recipient:c.company,address:c.address,zip:c.zip,city:c.city,country:'Suomi',info:''}],billingAddress:c.billing,history:[]}})}
  function initial(){const cs=customers(),vs=vendors();return{customers:cs,vendors:vs,orders:orders(cs,vs),margin:1.55}}
  let state;try{state=JSON.parse(localStorage.getItem(STORAGE_KEY)||'null')}catch(_e){}if(!state||!Array.isArray(state.orders)||!Array.isArray(state.customers)||!Array.isArray(state.vendors))state=initial();
  window.st=state;
  window.save=()=>localStorage.setItem(STORAGE_KEY,JSON.stringify(window.st));
  window.C=id=>window.st.customers.find(x=>String(x.id)===String(id));
  window.V=id=>window.st.vendors.find(x=>String(x.id)===String(id));
  window.logEvent=(order,text)=>{order.history=Array.isArray(order.history)?order.history:[];order.history.push({at:new Date().toISOString(),text})};
  window.resetDemo=()=>{if(!confirm('Palautetaanko demo 20 tarjoukseen ja 20 tilaukseen?'))return;window.st=initial();save();renderAll()};
})();
