/* CopySet ERP — clean full-page Tilaus view, authoritative navigation */
(function(){
 const esc=v=>String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const euro=n=>(Number(n)||0).toLocaleString('fi-FI',{minimumFractionDigits:2,maximumFractionDigits:2})+' €';
 const date=v=>{if(!v)return '—';try{return typeof FI_DATE==='function'?FI_DATE(v):v}catch(_e){return v}};
 /* app-base owns state as lexical `st`; it is not guaranteed to exist as window.st. */
 const state=()=>{try{return typeof st!=='undefined'?st:window.st}catch(_e){return window.st}};
 const get=id=>{const s=state();return s&&Array.isArray(s.orders)?s.orders.find(o=>String(o.id)===String(id)):null};
 const products=o=>Array.isArray(o.products)&&o.products.length?o.products:[{name:o.product,qty:o.qty,price:o.price,desc:o.description,extras:o.extraLines||[]}];
 function totals(o){try{if(typeof invoiceTotals==='function')return invoiceTotals(typeof normalizeOrder==='function'?normalizeOrder(o):o)}catch(_e){}const sales=products(o).reduce((s,p)=>s+(+p.price||0),0)+(+o.setupFee||0)+(+o.billingFee||0)+(+o.deliveryFee||0);return{net:sales,total:sales}}
 function cost(o){return +(o.cost||o.productionCost||o.totalCost||0)}
 function missing(o){const a=[];if(!o.artworkStatus||!/ok/i.test(o.artworkStatus))a.push('Aineisto OK');return a}
 function productCard(p,i){const extras=Array.isArray(p.extras)?p.extras:[];const specs=[p.size||p.format||p.koko,p.material||p.paper||p.materiaali||p.paperi,p.colors||p.color||p.varit||p['värit'],p.finishing||p.finish||p.jalkikasittely||p['jälkikäsittely']].filter(Boolean);return `<article class="op-product"><div class="op-product-head"><div><small>TUOTE ${i+1}</small><h3>${esc(p.name||'Tuote')}</h3></div><div><b>${esc(p.qty||0)} kpl</b><strong>${euro(p.price)}</strong></div></div>${specs.length?`<div class="op-specs">${specs.map(x=>`<span>${esc(x)}</span>`).join('')}</div>`:''}${p.desc?`<p>${esc(p.desc)}</p>`:''}${extras.length?`<div class="op-extras"><b>Työvaiheet / lisätyöt</b>${extras.map(x=>`<span>✓ ${esc(typeof x==='string'?x:(x.label||x.name||x.desc||'Lisätyö'))}</span>`).join('')}</div>`:''}</article>`}
 function closePage(){document.getElementById('copyset-order-page')?.remove();document.body.classList.remove('op-open');document.querySelectorAll('.modal.on').forEach(x=>x.classList.remove('on'))}
 window.copysetBackToOrders=closePage;
 function start(id){const o=get(id);if(!o)return false;o.mode='Tilaus';o.status='Tuotannossa';o.productionStep='Aloitettu';o.artworkStatus='Aineisto OK';if(typeof logEvent==='function')try{logEvent(o,'Tuotanto aloitettu')}catch(_e){};if(typeof window.copysetPrintWorkCard==='function')window.copysetPrintWorkCard(id);if(typeof save==='function')save();if(typeof renderAll==='function')renderAll();render(id);return true}
 window.copysetStartProduction=start;
 function nextAction(o){if(o.status==='Vahvistettu')return['Aloita tuotanto →',()=>start(o.id)];if(o.status==='Tuotannossa')return['Kuittaa valmiiksi →',()=>{if(typeof v2Advance==='function')v2Advance(o.id);setTimeout(()=>render(o.id),0)}];if(o.status==='Valmis')return['Siirrä laskun tarkastukseen →',()=>{if(typeof v2Advance==='function')v2Advance(o.id);setTimeout(()=>render(o.id),0)}];if(o.status==='Laskutusvalmis')return['Hyväksy lasku →',()=>{if(typeof v2Advance==='function')v2Advance(o.id);setTimeout(()=>render(o.id),0)}];return null}
 function render(id){
   const o=get(id);if(!o||o.mode==='Tarjous')return false;
   document.querySelectorAll('.modal.on').forEach(x=>x.classList.remove('on'));document.getElementById('copyset-order-page')?.remove();
   const t=totals(o),c=cost(o),margin=(+t.net||0)-c,pct=t.net?margin/t.net*100:0,warn=missing(o),ps=products(o),ship=o.shipping||o.deliveryMethod||'—';
   const wf=['Vahvistettu','Tuotannossa','Valmis','Laskutusvalmis','Laskutettu'],cur=Math.max(0,wf.indexOf(o.status)),n=nextAction(o),el=document.createElement('div');el.id='copyset-order-page';
   el.innerHTML=`<div class="op-top"><button id="opBack">← Takaisin tilauksiin</button><div><b>${esc(o.no||'Tilaus')}</b><span>${esc(o.company||'')} · ${esc(ps[0]?.name||'')} · Deadline ${date(o.deadline)}</span></div><em>${esc(o.status||'')}</em></div><main class="op-main"><section class="op-workflow">${wf.map((s,i)=>`<div class="${i<cur?'done':i===cur?'active':''}"><i>${i<cur?'✓':i+1}</i><span>${s}</span></div>`).join('')}</section>${warn.length?`<section class="op-warning"><b>⚠ Puuttuva tieto</b><span>${warn.map(esc).join(', ')}</span></section>`:''}<section class="op-section"><div class="op-title"><h2>Tuotteet ja työvaiheet</h2><span>${ps.length} tuotetta</span></div>${ps.map(productCard).join('')}</section><section class="op-info"><div><small>ASIAKAS</small><b>${esc(o.company||'—')}</b><span>${esc(o.email||'')}</span><span>${esc(o.phone||'')}</span><span>${esc([o.address,o.zip,o.city].filter(Boolean).join(', '))}</span></div><div><small>TOIMITUS</small><b>${esc(ship)}</b><span>${esc(o.deliveryAddress||'')}</span></div><div><small>DEADLINE</small><b>${date(o.deadline)}</b><span>Tilauspäivä ${date(o.date)}</span></div></section><section class="op-profit"><div><small>Myynti alv 0</small><b>${euro(t.net)}</b></div><div><small>Kustannus</small><b>${euro(c)}</b></div><div><small>Kate</small><b>${euro(margin)}</b></div><div><small>Kate-%</small><b>${pct.toFixed(1)} %</b></div></section><section class="op-two"><div class="op-box"><h3>Liitteet</h3><p>${o.attachments?.length?o.attachments.length+' tiedostoa':'Ei liitteitä'}</p></div><div class="op-box"><h3>Poikkeama / huomio</h3><p>${esc(o.deviation||o.note||o.notes||'Ei poikkeamia.')}</p></div></section><details class="op-history"><summary>Muutoshistoria (${Array.isArray(o.history)?o.history.length:0})</summary><div>${Array.isArray(o.history)&&o.history.length?o.history.map(x=>`<p>${esc(typeof x==='string'?x:(x.text||x.label||JSON.stringify(x)))}</p>`).join(''):'<p>Ei historiaa.</p>'}</div></details><section class="op-docs"><h3>Asiakirjat</h3><div><button id="opConfirm">Tilausvahvistus</button><button id="opWork">Työkortti tuotantoon <small>ei hintoja</small></button><button id="opDelivery">Lähete</button><button id="opLabel">Lähetyslappu</button></div></section><footer class="op-actions"><div><button id="opCopy">Kopioi uudeksi tilaukseksi</button><button id="opEdit">Muokkaa</button></div>${n?`<button class="op-primary" id="opNext">${n[0]}</button>`:''}</footer></main>`;
   document.body.appendChild(el);document.body.classList.add('op-open');
   el.querySelector('#opBack').onclick=closePage;el.querySelector('#opWork').onclick=()=>window.copysetPrintWorkCard?.(o.id);el.querySelector('#opConfirm').onclick=()=>{if(typeof showOrderConfirmation==='function')showOrderConfirmation(o.id);else if(typeof showConfirmation==='function')showConfirmation(o.id)};el.querySelector('#opDelivery').onclick=()=>{if(typeof showDeliveryNote==='function')showDeliveryNote(o.id)};el.querySelector('#opLabel').onclick=()=>{if(typeof showShippingLabel==='function')showShippingLabel(o.id)};el.querySelector('#opCopy').onclick=()=>{if(typeof copyOrder==='function')copyOrder(o.id);else if(typeof duplicateOrder==='function')duplicateOrder(o.id)};el.querySelector('#opEdit').onclick=()=>{closePage();if(typeof editOrder==='function')editOrder(o.id)};if(n)el.querySelector('#opNext').onclick=n[1];return true;
 }
 window.copysetOpenOrderPage=render;
 document.addEventListener('click',function(e){const el=e.target.closest&&e.target.closest('[onclick*="openOrder("]');if(!el)return;const code=el.getAttribute('onclick')||'',m=code.match(/openOrder\(['\"]([^'\"]+)['\"]\)/);if(!m)return;const o=get(m[1]);if(!o||o.mode==='Tarjous')return;e.preventDefault();e.stopPropagation();e.stopImmediatePropagation();render(m[1])},true);
 setTimeout(function(){const fallback=window.openOrder;window.openOrder=function(id){const o=get(id);if(o&&o.mode!=='Tarjous')return render(id);return typeof fallback==='function'?fallback.apply(this,arguments):undefined}},0);
})();