/* CopySet ERP — stage-specific full-page order workflow */
(function(){
 const root=window.CopySet=window.CopySet||{};
 const esc=v=>String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const number=v=>root.parseNumber?root.parseNumber(v,0):(Number(v)||0);
 const euro=v=>root.formatMoney?root.formatMoney(v):number(v).toLocaleString('fi-FI',{minimumFractionDigits:2,maximumFractionDigits:2})+' €';
 const date=v=>v?(root.formatDate?root.formatDate(v):String(v)):'—';
 const get=id=>root.getOrder?.(id)||null;
 const products=o=>Array.isArray(o.products)&&o.products.length?o.products:[{name:o.product,qty:o.qty,price:o.price,desc:o.description,extras:o.extraLines||[]}];
 function totals(o){try{if(typeof invoiceTotals==='function')return invoiceTotals(typeof normalizeOrder==='function'?normalizeOrder(o):o)}catch(_e){}const net=products(o).reduce((s,p)=>s+number(p.price),0)+number(o.setupFee)+number(o.billingFee)+number(o.deliveryFee);return{net,total:net}}
 function close(){document.getElementById('copyset-order-page')?.remove();document.body.classList.remove('op-open');document.querySelectorAll('.modal.on').forEach(x=>x.classList.remove('on'))}
 window.copysetBackToOrders=close;
 function addr(o){const d=Array.isArray(o.deliveries)&&o.deliveries.length?o.deliveries[0]:{};return{name:d.recipient||o.deliveryRecipient||o.company||'',address:d.address||o.deliveryAddress||o.address||'',zip:d.zip||o.deliveryZip||o.zip||'',city:d.city||o.deliveryCity||o.city||'',country:d.country||o.deliveryCountry||''}}
 function printDoc(title,body){const w=window.open('','_blank');if(!w)return alert('Salli ponnahdusikkuna asiakirjaa varten.');w.document.open();w.document.write(`<!doctype html><meta charset="utf-8"><title>${esc(title)}</title><style>@page{size:A4;margin:14mm}body{font-family:Arial;color:#202428}.doc{max-width:850px;margin:auto}.head{display:flex;justify-content:space-between;border-bottom:6px solid #ef7f1a;padding-bottom:14px}.brand{font-size:28px;font-weight:900}.brand span{color:#ef7f1a}.box{border:1px solid #ddd;border-radius:8px;padding:12px;margin:14px 0}table{width:100%;border-collapse:collapse}th,td{text-align:left;padding:10px;border-bottom:1px solid #ddd}.label{max-width:620px;margin:30px auto;border:3px solid #111;padding:28px}.to{font-size:22px;line-height:1.5;margin:25px 0}</style>${body}<script>onload=()=>print()<\/script>`);w.document.close()}
 function deliveryNote(id){const o=get(id);if(!o)return;const a=addr(o),ps=products(o);printDoc('Lähete '+o.no,`<main class="doc"><header class="head"><div class="brand">COPY<span>-SET</span></div><h1>LÄHETE ${esc(o.no||'')}</h1></header><div class="box"><b>${esc(a.name)}</b><br>${esc(a.address)}<br>${esc((a.zip+' '+a.city).trim())}</div><table>${ps.map(p=>`<tr><td><b>${esc(p.name||'Tuote')}</b></td><td>${esc(p.qty||0)} kpl</td><td>${esc(p.desc||'')}</td></tr>`).join('')}</table></main>`)}
 function shippingLabel(id){const o=get(id);if(!o)return;const a=addr(o);printDoc('Lähetyslappu '+o.no,`<main class="label"><div class="brand">COPY<span>-SET</span></div><div class="to"><b>${esc(a.name)}</b><br>${esc(a.address)}<br><b>${esc((a.zip+' '+a.city).trim())}</b></div><b>Tilaus ${esc(o.no||'')}</b></main>`)}
 window.copysetDeliveryNote=deliveryNote;window.copysetShippingLabel=shippingLabel;
 function refresh(o){root.persist?.();render(o.id)}
 function start(id){const o=get(id);if(!o)return;root.setStatus?.(id,'Tuotannossa','Tuotanto aloitettu');o.productionStep='Aloitettu';if(typeof window.copysetPrintWorkCard==='function')window.copysetPrintWorkCard(id);root.save?.();render(id)}
 function ready(id){const o=get(id);if(!o)return;root.setStatus?.(id,'Valmis','Tuotanto valmis');render(id)}
 function review(id){return window.copysetMoveToInvoiceReview?.(id)}
 function workflow(o){const wf=root.statuses||['Vahvistettu','Tuotannossa','Valmis','Laskutusvalmis','Laskutettu'],cur=Math.max(0,wf.indexOf(o.status));return `<section class="op-workflow">${wf.map((s,i)=>`<div class="${i<cur?'done':i===cur?'active':''}"><i>${i<cur?'✓':i+1}</i><span>${s}</span></div>`).join('')}</section>`}
 function productsHtml(o,prices=true){const ps=products(o);return `<section class="op-section"><div class="op-title"><h2>Tuotteet ja työvaiheet</h2><span>${ps.length} tuotetta</span></div>${ps.map((p,i)=>`<article class="op-product"><div class="op-product-head"><div><small>TUOTE ${i+1}</small><h3>${esc(p.name||'Tuote')}</h3></div><div><b>${esc(p.qty||0)} kpl</b>${prices?`<strong>${euro(p.price)}</strong>`:''}</div></div>${p.desc?`<p>${esc(p.desc)}</p>`:''}</article>`).join('')}</section>`}
 function docs(o,which){const buttons=[];if(which.includes('confirm'))buttons.push('<button id="opConfirm">Tilausvahvistus</button>');if(which.includes('work'))buttons.push('<button id="opWork">Työkortti tuotantoon <small>ei hintoja</small></button>');if(which.includes('delivery'))buttons.push('<button id="opDelivery">Lähete <small>ei hintoja</small></button>','<button id="opLabel">Lähetyslappu</button>');return buttons.length?`<section class="op-docs"><h3>Asiakirjat</h3><div>${buttons.join('')}</div></section>`:''}
 function stage(o){const t=totals(o),ship=o.shipping||o.deliveryMethod||'—';if(o.status==='Vahvistettu')return `${productsHtml(o)}<section class="op-info"><div><small>ASIAKAS</small><b>${esc(o.company||'—')}</b></div><div><small>TOIMITUS</small><b>${esc(ship)}</b></div><div><small>DEADLINE</small><b>${date(o.deadline)}</b></div></section>${docs(o,['confirm','work'])}`;
 if(o.status==='Tuotannossa')return `${productsHtml(o,false)}<section class="op-info"><div><small>TYÖVAIHE</small><b>${esc(o.productionStep||'Aloitettu')}</b></div><div><small>TOIMITUS</small><b>${esc(ship)}</b></div><div><small>DEADLINE</small><b>${date(o.deadline)}</b></div></section>${docs(o,['work'])}`;
 if(o.status==='Valmis')return `<section class="op-section"><div class="op-title"><h2>Valmis toimitukseen</h2><span>${products(o).length} tuotetta</span></div><p><b>${esc(o.company||'')}</b> · ${products(o).map(p=>esc(p.name||'Tuote')+' '+esc(p.qty||0)+' kpl').join(', ')} · ${esc(ship)}</p></section>${docs(o,['delivery'])}`;
 if(o.status==='Laskutusvalmis')return `<section class="op-section"><div class="op-title"><h2>Lasku odottaa tarkastusta</h2></div><p><b>${esc(o.company||'')}</b> · ${esc(o.no||'')} · Veroton ${euro(t.net)}</p></section>`;
 return `<section class="op-section"><div class="op-title"><h2>✓ Laskutettu</h2></div><div class="op-info"><div><small>TILAUS</small><b>${esc(o.no||'')}</b></div><div><small>ASIAKAS</small><b>${esc(o.company||'')}</b></div><div><small>LASKUTETTU</small><b>${date(o.invoicedAt||o.invoiceApprovedAt)}</b></div></div></section>`}
 function action(o){if(o.status==='Vahvistettu')return['Aloita tuotanto →',()=>start(o.id)];if(o.status==='Tuotannossa')return['Kuittaa valmiiksi →',()=>ready(o.id)];if(o.status==='Valmis')return['Siirrä laskun tarkastukseen →',()=>review(o.id)];if(o.status==='Laskutusvalmis')return['Tarkista lasku →',()=>review(o.id)];return null}
 function bind(el,o){el.querySelector('#opBack').onclick=close;el.querySelector('#opWork')&&(el.querySelector('#opWork').onclick=()=>window.copysetPrintWorkCard?.(o.id));el.querySelector('#opConfirm')&&(el.querySelector('#opConfirm').onclick=()=>typeof showOrderConfirmation==='function'?showOrderConfirmation(o.id):showConfirmation?.(o.id));el.querySelector('#opDelivery')&&(el.querySelector('#opDelivery').onclick=()=>deliveryNote(o.id));el.querySelector('#opLabel')&&(el.querySelector('#opLabel').onclick=()=>shippingLabel(o.id));el.querySelector('#opCopy')&&(el.querySelector('#opCopy').onclick=()=>typeof copyOrder==='function'?copyOrder(o.id):duplicateOrder?.(o.id));el.querySelector('#opEdit')&&(el.querySelector('#opEdit').onclick=()=>{close();editOrder?.(o.id)});const a=action(o);if(a&&el.querySelector('#opNext'))el.querySelector('#opNext').onclick=a[1]}
 function render(id){const o=get(id);if(!o||o.mode==='Tarjous')return false;document.querySelectorAll('.modal.on').forEach(x=>x.classList.remove('on'));document.getElementById('copyset-order-page')?.remove();const a=action(o),el=document.createElement('div');el.id='copyset-order-page';el.innerHTML=`<div class="op-top"><button id="opBack">← Takaisin tilauksiin</button><div><b>${esc(o.no||'Tilaus')}</b><span>${esc(o.company||'')} · ${esc(o.status||'')}</span></div><em>${esc(o.status||'')}</em></div><main class="op-main">${workflow(o)}${stage(o)}<details class="op-history"><summary>Muutoshistoria (${Array.isArray(o.history)?o.history.length:0})</summary></details><footer class="op-actions"><div>${o.status!=='Laskutettu'?'<button id="opCopy">Kopioi uudeksi tilaukseksi</button><button id="opEdit">Muokkaa</button>':''}</div>${a?`<button class="op-primary" id="opNext">${a[0]}</button>`:''}</footer></main>`;document.body.appendChild(el);document.body.classList.add('op-open');bind(el,o);return true}
 root.orderPage=Object.freeze({open:render,close,startProduction:start,markReady:ready,deliveryNote,shippingLabel});
 window.copysetOpenOrderPage=render;window.copysetStartProduction=start;
})();