/* CopySet ERP — canonical Tilaukset list */
(function(){
  const root=window.CopySet=window.CopySet||{};
  const ui={filter:'Kaikki',query:''};
  const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const products=o=>Array.isArray(o.products)&&o.products.length?o.products:[{name:o.product||'Tuote',qty:o.qty||0}];
  const statusClass=status=>String(status||'').toLowerCase().replace(/[^a-z0-9åäö]+/gi,'-');
  const dateValue=value=>root.parseDate?.(value)?.getTime()??Number.MAX_SAFE_INTEGER;
  const late=o=>{if(!o.deadline||['Valmis','Laskutusvalmis','Laskutettu'].includes(o.status))return false;const date=root.parseDate?.(o.deadline);if(!date)return false;date.setHours(23,59,59,999);return date.getTime()<Date.now()};
  const matches=(o,filter)=>filter==='Kaikki'||(filter==='Myöhässä'?late(o):o.status===filter);
  const nextLabel=o=>({Vahvistettu:'Aloita tuotanto',Tuotannossa:'Kuittaa valmiiksi',Valmis:'Laskun tarkastus',Laskutusvalmis:'Tarkista lasku'}[o.status]||'Avaa');
  function advance(id){const o=root.getOrder?.(id);if(!o)return false;if(o.status==='Vahvistettu')return root.actions?.startProduction?.(id);if(o.status==='Tuotannossa')return root.orderPage?.markReady?.(id);if(o.status==='Valmis'||o.status==='Laskutusvalmis')return root.invoiceReview?.move?.(id);return root.orderPage?.open?.(id)}
  function render(){const host=document.getElementById('orders'),state=root.state?.();if(!host||!state)return;const all=(state.orders||[]).filter(o=>(o.mode||'Tilaus')!=='Tarjous').map(o=>({...o,products:products(o)}));let visible=all.filter(o=>matches(o,ui.filter)).sort((a,b)=>dateValue(a.deadline)-dateValue(b.deadline));if(ui.query){const z=ui.query.toLocaleLowerCase('fi-FI');visible=visible.filter(o=>[o.no,o.company,...o.products.flatMap(p=>[p.name,p.qty])].some(v=>String(v??'').toLocaleLowerCase('fi-FI').includes(z)))}const filters=['Kaikki','Vahvistettu','Tuotannossa','Valmis','Laskutusvalmis','Laskutettu','Myöhässä'];const count=f=>all.filter(o=>matches(o,f)).length;const row=o=>`<tr data-order-id="${esc(o.id)}" style="cursor:pointer"><td><b>${esc(o.no)}</b></td><td><b>${esc(root.formatDate?root.formatDate(o.deadline):o.deadline)}</b>${late(o)?'<div class="small" style="color:#b42318;font-weight:800">MYÖHÄSSÄ</div>':''}</td><td>${esc(o.company)}</td><td>${o.products.map(p=>`${esc(p.name)} · ${esc(p.qty)}`).join('<br>')}</td><td><span class="badge ${statusClass(o.status)}">${esc(o.status)}</span></td><td>${o.status==='Laskutettu'?'<span class="small">✓ Valmis</span>':`<button class="btn orange" data-action="advance" data-id="${esc(o.id)}">${esc(nextLabel(o))} →</button>`}</td></tr>`;host.innerHTML=`<div class="list-shell"><div class="list-tools"><input id="search" placeholder="Hae tilausnumero, asiakas tai tuote" value="${esc(ui.query)}"><button class="btn orange list-create" onclick="newOrder('Tilaus')">+ Uusi tilaus</button><div class="list-filters">${filters.map(f=>`<button class="list-filter ${ui.filter===f?'on':''} ${f==='Myöhässä'?'late':''}" data-order-filter="${esc(f)}">${f==='Myöhässä'?'⚠ ':''}${esc(f)}<span class="count">${count(f)}</span></button>`).join('')}</div></div><div class="tablewrap"><table><thead><tr><th>Tilaus</th><th>Deadline</th><th>Asiakas</th><th>Tuotteet</th><th>Status</th><th>Seuraava vaihe</th></tr></thead><tbody>${visible.length?visible.map(row).join(''):'<tr><td colspan="6"><div class="order-empty">Ei tilauksia tällä rajauksella.</div></td></tr>'}</tbody></table></div></div>`;host.querySelectorAll('[data-order-filter]').forEach(button=>button.addEventListener('click',()=>{ui.filter=button.dataset.orderFilter;render()}));host.querySelectorAll('[data-order-id]').forEach(tr=>tr.addEventListener('click',()=>root.orderPage?.open?.(tr.dataset.orderId)));host.querySelectorAll('[data-action="advance"]').forEach(button=>button.addEventListener('click',event=>{event.stopPropagation();advance(button.dataset.id)}));const input=host.querySelector('#search');if(input)input.addEventListener('input',event=>{ui.query=event.target.value;render();const next=host.querySelector('#search');if(next){next.focus();next.setSelectionRange(next.value.length,next.value.length)}})}
  root.ordersUi=ui;root.renderOrders=render;
})();
