/* CopySet ERP — central pricing administration and defaults. */
(function(){
 const root=window.CopySet=window.CopySet||{},KEY='copyset-pricing-defaults-v1';
 const base={fees:{setupFee:50,billingFee:6,domesticVat:25.5,exportVat:0,paymentTermsDays:21},calculation:{waste:5,margin:1.55,rush:25},sizes:[['85×55 mm',1,0],['90×50 mm',1.02,0],['55×55 mm neliö',1.1,15]],materials:[['300 g',1,0],['350 g',1.12,0],['400 g luonnonkartonki',1.35,10]],prints:[['1-puolinen',1,0],['2-puolinen',1.45,12]],extras:[['Laminointi',23.5],['Pyöristetyt kulmat',27],['Foliointi',81],['Kohdelakka / UV-lakka',70],['Preglaus / kohokuvio',95],['Muotoleikkaus / stanssaus',89],['Personointi',48]],products:[]};
 const clone=v=>JSON.parse(JSON.stringify(v)),num=(v,d=0)=>{const n=Number(String(v??'').replace(',','.'));return Number.isFinite(n)?n:d},esc=v=>String(v??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;',"'":'&#39;'}[c]));
 function catalog(){try{return typeof P!=='undefined'&&Array.isArray(P)?P:[]}catch(_e){return[]}}
 const originalProducts=clone(catalog());
 function read(){let saved={};try{saved=JSON.parse(localStorage.getItem(KEY)||'{}')||{}}catch(_e){}const d={...clone(base),...saved,fees:{...base.fees,...saved.fees},calculation:{...base.calculation,...saved.calculation}};if(!Array.isArray(d.products)||!d.products.length)d.products=clone(originalProducts);return d}
 let settings=read();
 function apply(){const p=catalog();if(p.length&&settings.products?.length)p.splice(0,p.length,...clone(settings.products));root.pricingDefaults=settings}
 function persist(next){settings=next;localStorage.setItem(KEY,JSON.stringify(settings));apply();document.dispatchEvent(new CustomEvent('copyset:pricing-defaults-changed',{detail:clone(settings)}));return settings}
 function money(v){return num(v).toLocaleString('fi-FI',{minimumFractionDigits:2,maximumFractionDigits:2})+' €'}
 function row3(type,row,i){return `<div class="price-admin-row price-admin-row3" data-list="${type}" data-i="${i}"><input data-k="0" value="${esc(row[0])}" aria-label="Nimi"><input data-k="1" type="number" step="0.01" value="${num(row[1])}" aria-label="Kerroin"><input data-k="2" type="number" step="0.01" value="${num(row[2])}" aria-label="Kiinteä lisä"><button type="button" class="price-admin-remove" title="Poista">×</button></div>`}
 function row2(type,row,i){return `<div class="price-admin-row price-admin-row2" data-list="${type}" data-i="${i}"><input data-k="0" value="${esc(row[0])}" aria-label="Nimi"><input data-k="1" type="number" step="0.01" value="${num(row[1])}" aria-label="Hinta"><button type="button" class="price-admin-remove" title="Poista">×</button></div>`}
 function product(row,i){return `<div class="price-admin-row price-admin-product" data-list="products" data-i="${i}"><input data-k="0" value="${esc(row[0])}" aria-label="Tuote"><input data-k="1" type="number" step="0.001" value="${num(row[1])}" aria-label="Yksikkökustannus"><input data-k="2" type="number" step="0.01" value="${num(row[2])}" aria-label="Aloitus"><button type="button" class="price-admin-remove" title="Poista">×</button></div>`}
 function card(title,help,headers,body,kind,cols=3){return `<section class="price-admin-card"><div class="price-admin-cardhead"><div><h3>${title}</h3><p>${help}</p></div><button type="button" class="btn" data-add="${kind}">+ Lisää</button></div><div class="price-admin-head price-admin-head${cols}">${headers.map(x=>`<span>${x}</span>`).join('')}<span></span></div><div data-rows="${kind}">${body}</div></section>`}
 function style(){if(document.getElementById('pricingAdminStyle'))return;const s=document.createElement('style');s.id='pricingAdminStyle';s.textContent=`
.price-admin{max-width:1240px;margin:0 auto}.price-admin-hero{display:flex;justify-content:space-between;gap:16px;align-items:center;padding:20px 22px;background:linear-gradient(135deg,#353535,#454545);color:#fff;border:0}.price-admin-hero h2{margin:0 0 5px;font-size:24px}.price-admin-hero p{margin:0;color:#d8d8d8}.price-admin-actions{display:flex;gap:8px;flex-wrap:wrap}.price-admin-save{background:#ef7f1a!important;color:#fff!important;border-color:#ef7f1a!important}.price-admin-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.price-admin-card{background:#fff;border:1px solid #dfe3e8;border-radius:13px;padding:15px;box-shadow:0 5px 18px rgba(30,38,45,.04)}.price-admin-card.wide{grid-column:1/-1}.price-admin-cardhead{display:flex;justify-content:space-between;gap:12px;align-items:flex-start;margin-bottom:10px}.price-admin-card h3{margin:0;font-size:16px}.price-admin-card p{margin:4px 0 0;color:#6b7280;font-size:11px}.price-admin-fees{display:grid;grid-template-columns:repeat(4,1fr);gap:10px}.price-admin-field label{display:block;margin-bottom:5px;color:#59636e;font-size:10px;font-weight:900;text-transform:uppercase}.price-admin-field input{min-height:42px}.price-admin-head,.price-admin-row{display:grid;gap:8px;align-items:center}.price-admin-head{padding:0 0 6px;color:#65707b;font-size:9px;font-weight:900;text-transform:uppercase}.price-admin-head3,.price-admin-row3,.price-admin-product{grid-template-columns:minmax(130px,1.5fr) minmax(80px,.65fr) minmax(80px,.65fr) 34px}.price-admin-head2,.price-admin-row2{grid-template-columns:minmax(150px,1fr) minmax(90px,.45fr) 34px}.price-admin-row{padding:6px 0;border-top:1px solid #edf0f2}.price-admin-row input{min-width:0;padding:8px}.price-admin-remove{height:34px;border:0;border-radius:8px;background:#fff0ef;color:#b42318;font-size:18px;font-weight:900}.price-admin-toast{display:none;margin:0 0 14px;padding:10px 13px;border-radius:9px;background:#e8f6ed;color:#196b38;font-weight:800}.price-admin-toast.on{display:block}@media(max-width:900px){.price-admin-grid{grid-template-columns:1fr}.price-admin-fees{grid-template-columns:repeat(2,1fr)}.price-admin-hero{align-items:flex-start;flex-direction:column}}@media(max-width:560px){.price-admin-fees{grid-template-columns:1fr}.price-admin-head{display:none}.price-admin-row3,.price-admin-product{grid-template-columns:1fr 1fr 34px}.price-admin-row3 input:first-child,.price-admin-product input:first-child{grid-column:1/3}.price-admin-row2{grid-template-columns:1fr 90px 34px}}
`;document.head.appendChild(s)}
 function render(){style();const host=document.getElementById('pricing');if(!host)return;settings=read();host.innerHTML=`<div class="price-admin"><div class="card price-admin-hero"><div><h2>Hinnoittelu</h2><p>Muokkaa oletushintoja. Tallennetut arvot tulevat automaattisesti uusiin tarjouksiin ja tilauksiin.</p></div><div class="price-admin-actions"><button type="button" class="btn" data-reset-pricing>Palauta oletukset</button><button type="button" class="btn price-admin-save" data-save-pricing>✓ Tallenna hinnasto</button></div></div><div class="price-admin-toast" role="status">✓ Hinnasto tallennettu. Uudet oletukset ovat nyt käytössä.</div><div class="price-admin-card wide" style="margin-bottom:14px"><div class="price-admin-cardhead"><div><h3>Yleiset oletukset</h3><p>Nämä arvot täytetään automaattisesti uusiin tarjouksiin ja tilauksiin.</p></div></div><div class="price-admin-fees">${[['setupFee','Aloituskustannus €'],['billingFee','Laskutuslisä €'],['domesticVat','ALV Suomi %'],['exportVat','ALV vienti %']].map(x=>`<div class="price-admin-field"><label>${x[1]}</label><input data-fee="${x[0]}" type="number" step="0.01" value="${num(settings.fees[x[0]])}"></div>`).join('')}<div class="price-admin-field"><label>Maksuehto pv</label><input data-fee="paymentTermsDays" type="number" step="1" value="${num(settings.fees.paymentTermsDays)}"></div><div class="price-admin-field"><label>Hukka %</label><input data-calc="waste" type="number" step="0.1" value="${num(settings.calculation.waste)}"></div><div class="price-admin-field"><label>Katekerroin</label><input data-calc="margin" type="number" step="0.01" value="${num(settings.calculation.margin)}"></div><div class="price-admin-field"><label>Kiirelisä %</label><input data-calc="rush" type="number" step="1" value="${num(settings.calculation.rush)}"></div></div></div><div class="price-admin-grid">${card('Tuotteet','Yksikkökustannus ja tuotekohtainen aloitus.',['Tuote','€/yks','Aloitus €'],settings.products.map(product).join(''),'products')}${card('Koot','Kerroin ja mahdollinen kiinteä lisä.',['Koko','Kerroin','Lisä €'],settings.sizes.map((r,i)=>row3('sizes',r,i)).join(''),'sizes')}${card('Materiaalit','Materiaalikerroin ja kiinteä lisä.',['Materiaali','Kerroin','Lisä €'],settings.materials.map((r,i)=>row3('materials',r,i)).join(''),'materials')}${card('Painatus','Yksi- ja kaksipuolisen työn oletukset.',['Painatus','Kerroin','Lisä €'],settings.prints.map((r,i)=>row3('prints',r,i)).join(''),'prints')}${card('Lisätyöt ja viimeistely','Oletushinta voidaan muuttaa vielä yksittäisessä työssä.',['Lisätyö','Hinta €'],settings.extras.map((r,i)=>row2('extras',r,i)).join(''),'extras',2)}</div></div>`;bind(host)}
 function collect(host){const next=clone(settings);host.querySelectorAll('[data-fee]').forEach(x=>next.fees[x.dataset.fee]=num(x.value));host.querySelectorAll('[data-calc]').forEach(x=>next.calculation[x.dataset.calc]=num(x.value));['products','sizes','materials','prints','extras'].forEach(type=>{next[type]=[...host.querySelectorAll(`[data-list="${type}"]`)].map(row=>[...row.querySelectorAll('[data-k]')].sort((a,b)=>num(a.dataset.k)-num(b.dataset.k)).map((x,i)=>i?num(x.value):x.value.trim())).filter(r=>r[0])});return next}
 function bind(host){host.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{const type=b.dataset.add,box=host.querySelector(`[data-rows="${type}"]`),row=type==='extras'?row2(type,['',0],999):type==='products'?product(['',0,0],999):row3(type,['',1,0],999);box.insertAdjacentHTML('beforeend',row);bind(host)});host.querySelectorAll('.price-admin-remove').forEach(b=>b.onclick=()=>b.closest('.price-admin-row')?.remove());host.querySelector('[data-save-pricing]').onclick=()=>{persist(collect(host));render();const toast=document.querySelector('.price-admin-toast');toast?.classList.add('on');setTimeout(()=>toast?.classList.remove('on'),2600)};host.querySelector('[data-reset-pricing]').onclick=()=>{if(!confirm('Palautetaanko kaikki hinnat alkuperäisiin oletuksiin?'))return;const reset=clone(base);reset.products=clone(originalProducts);persist(reset);render()}}
 apply();root.pricingSettings=Object.freeze({get:()=>clone(settings),save:persist,render});root.renderPricing=render;window.renderPricing=render;document.addEventListener('copyset:clean-ready',render);
})();
