/* CopySet ERP — canonical offer review, send and rejection actions. */
(function(){
 const root=window.CopySet=window.CopySet||{},esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const get=id=>root.getOrder?.(id),body=()=>document.getElementById('mb'),modal=()=>document.getElementById('modal'),title=()=>document.getElementById('mt');
 const products=o=>Array.isArray(o.products)&&o.products.length?o.products:[{name:o.product,qty:o.qty,price:o.price,desc:o.description}];
 function stage(o){return o.quoteStage||o.offerStatus||'Luonnos'}
 function total(o){return products(o).reduce((s,p)=>s+(root.parseNumber?.(p.price,0)||0),0)+(root.parseNumber?.(o.setupFee,0)||0)+(root.parseNumber?.(o.billingFee,0)||0)+(root.parseNumber?.(o.deliveryPrice,0)||0)}
 function reviewHtml(o){return `<div class="quote-review"><div class="review-grid"><div class="review-card"><h4>ASIAKAS</h4><b>${esc(o.company)}</b><p>${esc(o.contact)}<br>${esc(o.email)} · ${esc(o.phone)}</p></div><div class="review-card"><h4>TARJOUSTIEDOT</h4><p>${esc(root.formatDate?.(o.date)||o.date)}<br>Voimassa ${esc(root.formatDate?.(o.valid)||o.valid)} asti</p></div></div><div class="card"><h3>Tuotteet ja työvaiheet</h3>${products(o).map(p=>`<div class="quote-product"><b>${esc(p.name)}</b><span>${esc(p.qty)} kpl</span><span>${root.formatMoney?.(p.price)||p.price}</span><p>${esc(p.desc||'')}</p></div>`).join('')}<div class="quote-total"><span>Yhteensä alv 0 %</span><b>${root.formatMoney?.(total(o))||total(o)}</b></div></div></div>`}
 function open(id){const o=get(id);if(!o)return false;title().textContent=`Tarjous · ${o.no}`;body().innerHTML=`<div class="mode-banner"><b>TARJOUS</b><span>${esc(stage(o))}</span></div>${reviewHtml(o)}<div class="actions quote-dialog-actions"><button class="btn" data-edit>Muokkaa</button>${stage(o)==='Luonnos'?'<button class="btn orange" data-check>Tarkista tarjous</button>':''}${stage(o)==='Valmis lähetettäväksi'?'<button class="btn orange" data-send>Avaa ja lähetä</button>':''}${stage(o)==='Lähetetty'?'<button class="btn orange" data-accept>✓ Asiakas hyväksyi</button>':''}${stage(o)==='Hyväksytty'?'<button class="btn orange" data-accept>Avaa / luo tilaus</button>':''}${!['Hyväksytty','Hylätty'].includes(stage(o))?'<button class="btn" data-reject>Hylkää tarjous</button>':''}</div>`;modal().classList.add('on');body().querySelector('[data-edit]')?.addEventListener('click',()=>root.orderForm?.edit?.(id));body().querySelector('[data-check]')?.addEventListener('click',()=>check(id));body().querySelector('[data-send]')?.addEventListener('click',()=>send(id));body().querySelector('[data-accept]')?.addEventListener('click',()=>root.quotes?.accept?.(id));body().querySelector('[data-reject]')?.addEventListener('click',()=>reject(id));return true}
 function check(id){const o=get(id);if(!o)return false;o.quoteStage=o.offerStatus='Valmis lähetettäväksi';o.quoteApproved=true;logEvent(o,'Tarjous tarkistettu ja hyväksytty lähettämistä varten');root.persist?.({render:false});root.renderQuotes?.();open(id);return true}
 function send(id){const o=get(id);if(!o)return false;o.quoteStage=o.offerStatus='Lähetetty';o.quoteSentAt=new Date().toISOString();logEvent(o,'Tarjous merkitty lähetetyksi asiakkaalle');root.persist?.({render:false});root.renderQuotes?.();open(id);return true}
 function reject(id){const o=get(id);if(!o||!confirm('Merkitäänkö tarjous hylätyksi?'))return false;o.quoteStage=o.offerStatus='Hylätty';logEvent(o,'Tarjous merkitty hylätyksi');root.persist?.({render:false});root.renderQuotes?.();open(id);return true}
 window.openQuoteWork=open;window.showPreflight=check;window.showQuote=send;window.rejectQuote=reject;root.quoteActions=Object.freeze({open,check,send,reject});
})();
