const products=[
 {key:'kayntikortit',name:'Käyntikortit',tag:'Yrityksen tärkein kädenjälki',desc:'Terävä painojälki, laadukkaat kartongit ja useita viimeistelyvaihtoehtoja.',sizes:['90 × 50 mm','85 × 55 mm','Oma koko'],materials:['300 g silk','350 g matt','400 g premium'],finishes:['Ei viimeistelyä','Mattalaminointi','Kiiltävä laminointi','Pyöristetyt kulmat']},
 {key:'flyerit',name:'Esitteet & flyerit',tag:'Kampanjat ja myynti',desc:'Yksi- tai monisivuiset materiaalit pienistä eristä suuriin kampanjoihin.',sizes:['A6','A5','A4','DL','Oma koko'],materials:['130 g silk','170 g silk','250 g matt'],finishes:['Ei viimeistelyä','Taitto','Mattalaminointi','Kiiltävä laminointi']},
 {key:'tarrat',name:'Tarrat & etiketit',tag:'Tuotteet, pakkaukset ja ikkunat',desc:'Lähes kaikki koot ja muodot sisä- ja ulkokäyttöön.',sizes:['Pyöreä 50 mm','A7','A6','Oma koko / muoto'],materials:['Paperitarra','Valkoinen vinyyli','Kirkas vinyyli'],finishes:['Suora leikkaus','Muotoonleikkaus','Mattalaminointi','Kiiltävä laminointi']},
 {key:'julisteet',name:'Julisteet & suurkuvat',tag:'Näy läheltä ja kaukaa',desc:'Julisteet, suurkuvat ja kampanjamateriaalit kaikkiin tiloihin.',sizes:['A3','A2','A1','A0','Oma koko'],materials:['170 g silk','200 g matt','Säänkestävä materiaali'],finishes:['Ei viimeistelyä','Mattalaminointi','Kiiltävä laminointi']},
 {key:'rollup',name:'Roll-upit',tag:'Messut ja tapahtumat',desc:'Helposti kuljetettava näyttävä ratkaisu, painatus ja teline valmiina.',sizes:['85 × 200 cm','100 × 200 cm'],materials:['Roll-up-materiaali'],finishes:['Vakio teline','Premium teline']},
 {key:'kortit',name:'Kortit & kutsut',tag:'Juhlat ja muistamiset',desc:'Kutsut, postikortit ja tervehdyskortit juuri sinun ilmeelläsi.',sizes:['A6','A5 taitettu','105 × 210 mm','Oma koko'],materials:['300 g silk','350 g matt','Erikoiskartonki'],finishes:['Ei viimeistelyä','Taitto','Foliointi','Pyöristetyt kulmat']},
 {key:'vihkot',name:'Vihkot & lehdet',tag:'Julkaisut ja esittelyt',desc:'Yrityslehdet, tuoteluettelot ja vihkot tarkasti viimeisteltynä.',sizes:['A5','A4','210 × 210 mm','Oma koko'],materials:['Sisus 100 g / kansi 250 g','Sisus 130 g / kansi 300 g'],finishes:['Vihkonidonta','Liimanidonta','Kierresidonta']},
 {key:'lomakkeet',name:'Lomakkeet & lehtiöt',tag:'Arjen toimivat painotuotteet',desc:'Itsejäljentävät lomakkeet, muistilehtiöt ja yrityksen vakiopohjat.',sizes:['A6','A5','A4','Oma koko'],materials:['80 g offset','Itsejäljentävä 2-osainen','Itsejäljentävä 3-osainen'],finishes:['Irtolomake','Liimaus lehtiöksi','Numerointi']}
];
let cart=JSON.parse(localStorage.getItem('copyset-cart')||'[]');let activeProduct=null;
function esc(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function card(p){return `<button class="product-card" data-key="${p.key}" onclick="openProduct('${p.key}')"><div class="product-visual"><span class="product-shape"></span></div><div class="product-content"><small>${esc(p.tag)}</small><h3>${esc(p.name)}</h3><p>${esc(p.desc)}</p></div><span class="product-arrow">↗</span></button>`}
function renderProducts(list=products){productGrid.innerHTML=list.map(card).join('');notFound.hidden=list.length>0}
function filterProducts(){const q=productSearch.value.trim().toLocaleLowerCase('fi');renderProducts(products.filter(p=>[p.name,p.tag,p.desc].join(' ').toLocaleLowerCase('fi').includes(q)))}
function focusSearch(){document.querySelector('#products').scrollIntoView({behavior:'smooth'});setTimeout(()=>productSearch.focus(),500)}
function openProduct(key){activeProduct=products.find(p=>p.key===key);productDetail.innerHTML=`<div class="detail-visual"><span class="product-shape"></span></div><p class="eyebrow orange">${esc(activeProduct.tag)}</p><h2 class="detail-title">${esc(activeProduct.name)}</h2><p class="detail-lead">${esc(activeProduct.desc)}</p><div class="chips"><span class="chip">Aineiston tarkistus</span><span class="chip">Nouto tai toimitus</span><span class="chip">Pienet ja suuret erät</span></div><div class="config"><label>Koko<select id="cfgSize">${activeProduct.sizes.map(x=>`<option>${esc(x)}</option>`).join('')}</select></label><label>Määrä<input id="cfgQty" type="number" min="1" value="100"></label><label>Materiaali<select id="cfgMaterial">${activeProduct.materials.map(x=>`<option>${esc(x)}</option>`).join('')}</select></label><label>Viimeistely<select id="cfgFinish">${activeProduct.finishes.map(x=>`<option>${esc(x)}</option>`).join('')}</select></label></div><p class="hint"><b>Aineisto:</b> Painovalmis PDF, 3 mm leikkuuvara ja kuvat 300 ppi. Voit lähettää aineiston myös myöhemmin.</p><button class="primary full" onclick="addToCart()">Lisää tarjouskoriin</button>`;showPanel(productPanel)}
function showPanel(el){overlay.classList.add('on');el.classList.add('on');el.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function closePanel(){overlay.classList.remove('on');document.querySelectorAll('.panel,.modal').forEach(x=>{x.classList.remove('on');x.setAttribute('aria-hidden','true')});document.body.style.overflow=''}
function closePanels(e){if(e.target===overlay)closePanel()}
function addToCart(){cart.push({name:activeProduct.name,size:cfgSize.value,qty:cfgQty.value,material:cfgMaterial.value,finish:cfgFinish.value});saveCart();closePanel();toastMsg(`${activeProduct.name} lisätty koriin`)}
function saveCart(){localStorage.setItem('copyset-cart',JSON.stringify(cart));cartCount.textContent=cart.length}
function openCart(){renderCart();showPanel(cartPanel)}
function renderCart(){cartItems.innerHTML=cart.length?cart.map((x,i)=>`<div class="cart-item"><div><h3>${esc(x.name)}</h3><p>${esc(x.qty)} kpl · ${esc(x.size)}<br>${esc(x.material)} · ${esc(x.finish)}</p></div><button onclick="removeCart(${i})">Poista</button></div>`).join(''):`<div class="cart-empty"><h3>Ostoskori on vielä tyhjä</h3><p>Valitse yksi suosituista tuotteista.</p></div>`;checkoutButton.disabled=!cart.length}
function removeCart(i){cart.splice(i,1);saveCart();renderCart()}
function openQuote(){closePanel();quoteModal.classList.add('on');quoteModal.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}
function startCheckout(){closePanel();openQuote();const ta=quoteModal.querySelector('textarea');ta.value='Tarjouskorin tuotteet:\n'+cart.map(x=>`• ${x.name}, ${x.qty} kpl, ${x.size}, ${x.material}, ${x.finish}`).join('\n')}
function submitQuote(e){e.preventDefault();const data=new FormData(e.target);const subject=encodeURIComponent('Tarjouspyyntö verkkosivulta');const body=encodeURIComponent(`Nimi / yritys: ${data.get('name')}\nSähköposti: ${data.get('email')}\nPuhelin: ${data.get('phone')||'—'}\n\n${data.get('message')}`);window.location.href=`mailto:copy-set@copy-set.fi?subject=${subject}&body=${body}`;closePanel();toastMsg('Tarjouspyyntö avattiin sähköpostiin.');e.target.reset()}
function toastMsg(msg){toast.textContent=msg;toast.classList.add('on');setTimeout(()=>toast.classList.remove('on'),2800)}
function toggleMenu(){mobileNav.classList.toggle('on')}
renderProducts();saveCart();
